apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcastservice
  labels:
    version: v1
spec:
  selector:
    matchLabels:
      app: broadcastservice
      version: v1
  template:
    metadata:
      labels:
        app: broadcastservice
        version: v1
    spec:
      terminationGracePeriodSeconds: 4
      containers:
      - name: server
        image: eu.gcr.io/bruno-1407a/broadcastservice:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
          - name: ws
            containerPort: 8081            
---
apiVersion: v1
kind: Service
metadata:
  name: broadcastservice
  labels:
    app: broadcastservice
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 8081
    name: ws
    targetPort: 8081    
  selector:
    app: broadcastservice
